# server port config
server:
  port: 8404


# driver config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql.coffit.today:3306/notfound
    username: notfound
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/thymeleaf-springboot/
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      check-template-location: true
    web:
      resources:
        static-locations: C:/thymeleaf-springboot/

image:
  image-dir: img


# mybatis config
mybatis:
  mapper-locations: mybatis/mappers/*.xml
  # alias Setting
  type-aliases-package: com.nf.not404found
  configuration:
    map-underscore-to-camel-case: true